# https://taskfile.dev

version: '3'

vars:
  OUT_DIR: dist
  OUT_FILE: smtp-cli
  OUT_ARCHIVE: smtp-cli

tasks:
  build:
    internal: true
    aliases:
      - build
      - compile
    vars:
      BUILD_VERSION: "{{ env \"BUILD_VERSION\" | default \"dev\" }}"
      BUILD_COMMIT:
        sh: git rev-parse --short HEAD
    cmd: |
      go build \
        -ldflags="{{.LDFLAGS}} -X 'main.Version={{.BUILD_VERSION}}' -X 'main.CommitHash={{.BUILD_COMMIT}}' -X 'main.BuildTimestamp={{ now }}'" \
        -o "{{.OUT_DIR}}/{{.OUT_FILE}}" \
        .
    deps:
      - clean

  default:
    cmds:
      - task: build:debug

  build:release:
    cmds:
      - task: build
        vars:
          LDFLAGS: -s -w
      - task: dist

  build:debug:
    cmds:
      - task: build
        vars:
          LDFLAGS: ""
      - task: dist

  dist:
    desc: Install additional files for release.
    cmds:
      - cp install.sh "{{.OUT_DIR}}/"
      - cp config/smtp-cli.json.example "{{.OUT_DIR}}/smtp-cli.json"
      - cp config/template.gotmpl.example "{{.OUT_DIR}}/template.gotmpl"
      - tar czvf "{{.OUT_ARCHIVE}}.tar.gz" "{{.OUT_DIR}}/"
    sources:
      - dist/**
    generates:
      - "{{.OUT_ARCHIVE}}.tar.gz"

  clean:
    cmd: rm -rf "{{.OUT_DIR}}"

  test:
    cmd: go test -v -cover -coverprofile=coverage.out ./...
