name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Build
        run: task build:debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            *.tar.gz
          retention-days: 5

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run tests
        run: task test
