name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUILD_VERSION: ${{ github.ref_name }}
      OUT_ARCHIVE: "${{ github.event.repository.name }}-${{ github.ref_name }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Build
        run: task build:release

      - id: extract-changelog
        uses: sean0x42/markdown-extract@v2
        with:
          file: CHANGELOG.md
          pattern: ${{ github.ref_name }}
          no-print-matched-heading: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ !env.ACT }}
        with:
          body: |
            ## Changelog
            ${{ steps.extract-changelog.outputs.markdown }}
          files: |
            *.tar.gz
